### ISSUE TITLE
Code clean up

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-csharp#10]
- [x] Namespaces should not contain vendor name and should be aligned with Java OC
- [x] unused usings
- [x] commented code
- [x] remove AsyncLocal OnChange subscription
- [x] code style checks
- [x] latest C# features: expression-bodied props, etc...
- [x] empty lines
- [x] sln project
- [x] gitignore
- [x] readme
- [x] making the enums pascal cased

**Comment by Falco20019** [comment]
I assume „code style checks“ includes making the enums pascal cased?

**Comment by lmolkova** [comment]
@Falco20019 
good point

**Comment by SergeyKanzhelev** [comment]
I believe this is done. Codebase is still having over 550 warnings from the undocumented public APIs. But those will be tracked separately
