### ISSUE TITLE
Timestamp, Clocks, TimestampConverter: are they needed

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-csharp#11]
Clean up time-related contracts. Most of them came as a port from Java SDK. After reviewing it I think we need the following:

- [ ] `Timestamp` class with nanosecond resolution. Make it struct. It should only used in `SpanData` as this resolution it only needed to be able to represent high-resolution clock - when you are importing data for instance, not to actually measure time in C# application. It may also be needed for stats `Views`, need more investigations.
- [ ] `IClock` should be removed as it is only used to abstract away `getNanos` system call in Java. The only promise of `IClock` is to give the start time of a span and `DateTimeOffset.Now` can do it well.
- [x] `TimesampConverter` is needed as it is used to calculate latency with high precision using `StopWatch` from the `startTime` of the outermost span. All children spans and time events should the same instance of `TimestampConverter` to ensure the durations and position of time events is monotonic and precise. Theoretically we can use `Stopwatch` class instead of using this wrapper. The only benefit of a wrapper is that it will encapsulate both - start time and stopwatch to generate high-precision start time.

**Comment by SergeyKanzhelev** [comment]
Those classes are needed for the nanoseconds precision. Ideally there should be better APIs for those that allow to work with well-known .NET classes like `DateTimeOffset` and `Timespan`. Especially for the API layer

**Comment by SergeyKanzhelev** [comment]
This will be handled in OpenTelemetry project
