### ISSUE TITLE
exporter/stackdriver: distribution range is not allowed

### ISSUE THREAD

**Issue by tadeuszwojcik** [census-instrumentation/opencensus-csharp#110]
I've tried using distribution aggregation with stackdriver exporter, but it does not work.
It looks like the same issue as in GO package - https://github.com/census-instrumentation/opencensus-go/issues/143

**Comment by simonz130** [comment]
Yes, distribution range is not supported yet. I see that Go has fixed it, so will take a look in the coming weeks to see if we are unblocked to add it to C# library too.

**Comment by sriramsa** [comment]
@simonz130, any updates?
Thanks in advance.

**Comment by SergeyKanzhelev** [comment]
Moved to OpenTelemetry
