### ISSUE TITLE
EF Core support

### ISSUE THREAD

**Issue by ekarlso** [census-instrumentation/opencensus-csharp#114]
Hi, is there a timeline for support for EF core and psql/mysql/mssql?

**Comment by simonz130** [comment]
No immediate timeline for this yet, but we discussed to have it.
I would imagine post April"19 at least.

**Comment by ekarlso** [comment]
@simon so late? what is the hold up?

**Comment by simonz130** [comment]
We have other commitments that we need to work on. If more folks volunteer to work on this, we might get to this sooner.

**Comment by SergeyKanzhelev** [comment]
Moved to OpenTelemetry
