### ISSUE TITLE
Support for distributed tracing when calls are made over message systems like NServiceBus, Rabbit MQ etc

### ISSUE THREAD

**Issue by senthildevi2019** [census-instrumentation/opencensus-csharp#115]

**Comment by SergeyKanzhelev** [comment]
Is suggestion to automatically inject headers? Or in general support these client libraries?

**Comment by jacostro** [comment]
I have a problem with a queuing scenario:
* web application queues a request for offline processing (trace A),
* pub/sub subscriber picks up a request and processes it (trace B).

These processes take place at different time and processing part (B) is usually longer. Both have separate traces, but top level span of trace B has a link (`LinkType.ParentLinkedSpan`) to originating span in trace A. I can see the link in Stackdriver. But it is not obvious how to find trace B from trace A view. So I would also like to have `LinkType.ChildLinkedSpan`-type link in trace A. For this purpose I need trace context of trace B, which does not exist yet. I can pre-generate and queue it, but API doesn't seem to contain functionality to start trace from specified context (trace and span ids). Closest to that is `ITracer.SpanBuilderWithRemoteParent` which at least will produce a trace with a given id.

What I miss for this scenario is something like:
```csharp
ITracer.SpanBuilderWithExplicitContext(string spanName, ISpanContext spanContext);
```

**Comment by SergeyKanzhelev** [comment]
Moved to OpenTelemetry https://github.com/open-telemetry/opentelemetry-dotnet/issues/78
