### ISSUE TITLE
Is Steeltoe version of Sleuth available?

### ISSUE THREAD

**Issue by senthildevi2019** [census-instrumentation/opencensus-csharp#116]

**Comment by SergeyKanzhelev** [comment]
@dtillman can you please help answering this?

**Comment by senthildevi2019** [comment]
https://howtodoinjava.com/spring-cloud/spring-cloud-zipkin-sleuth-tutorial/

Sleuth is in java. do we have any wrapper for this in .Net or Steeltoe?

**Comment by senthildevi2019** [comment]
How can I do tracing for Message systems like RabbitMQ, NServiceBus when using Zipkin?

**Comment by SergeyKanzhelev** [comment]
@senthildevi2019 you can trace calls to RabbitMQ by calling `StartSpan` API. There is no auto-collector today so you'd need to use API directly to wrap your calls.

**Comment by senthildevi2019** [comment]
Can you add more details? Some code snippets if any..

**Comment by SergeyKanzhelev** [comment]
@senthildevi2019 this doc gives an introduction in tracing API: https://opencensus.io/quickstart/dotnet/tracing/ Let me know if you need more info

**Comment by senthildevi2019** [comment]
Thank you .. let me try it out and update you
