### ISSUE TITLE
One of ApplicationInsights tests blocks CI

### ISSUE THREAD

**Issue by lkts** [census-instrumentation/opencensus-csharp#117]
Hi,

Thank you for working on this project. I tried to get latest beta build from MyGet today (i am particularly interested in https://github.com/census-instrumentation/opencensus-csharp/pull/109) and realized that CI is red from the end of January.

Failing test is `OpenCensus.Exporter.ApplicationInsights.Tests.OpenCensusTelemetryConverterTests.OpenCensusTelemetryConverterTests_TracksRequestWithAnnotations` which fails on `Assert.NonEqual`. I do not have enough knowledge to understand why it fails.

Thanks.

**Comment by SergeyKanzhelev** [comment]
Should be fixed now

**Comment by lkts** [comment]
Thanks!
