### ISSUE TITLE
Support for CNCF Jaeger

### ISSUE THREAD

**Issue by rstraszewski** [census-instrumentation/opencensus-csharp#118]
Hi! 
Is Jaeger exporter considered?

**Comment by SergeyKanzhelev** [comment]
Happy to accept contribution. Will Zipkin exporter work with Jaeger in your scenario?

**Comment by rstraszewski** [comment]
We want to use Jaeger to monitor our system. Our current solution is not suited for microservices architecture. Until now we only considered native integration and Jaeger dotnet library. I know about Jaeger being compatible with zipkin traces, but we would need to compare this two solutions and see if there are any downfalls of using zipkin compatible mode. I just wanted to know if there are any plans for native integration :)  Thanks!

**Comment by SergeyKanzhelev** [comment]
We don't have immediate plans, but we will be happy to accept contribution

**Comment by SergeyKanzhelev** [comment]
Moved to https://github.com/open-telemetry/opentelemetry-dotnet/issues/77
