### ISSUE TITLE
Error logging with EventSource

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-csharp#12]
We typically log all internal errors/warning/traces to EventSource in other .NET libs.

**Comment by lmolkova** [comment]
Here is the sample: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/10d2cacbdced85836c36e67f663a897efeb97359/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Tracing/CoreEventSource.cs

documentation: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource?view=netcore-2.2. 

Using EventSource does not require any additional dependencies (such as logging nuget). It also works out of process and is extremely lightweight.
These events represent internal diagnostics of opencensus and in majority of cases are not interesting to users.

It does not actually have a schema, every event has a strict signature.

**Comment by SergeyKanzhelev** [comment]
Moved to OpenTelemetry
