### ISSUE TITLE
Allow to implement specific component listeners leveraging ListenerHandler

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-csharp#129]
When someone wants to implement a new listener for the component we don't support out of the box, they should be able to leverage DiagnosticListener subscription, and perhaps property fetching.

The first step could be making OpenCensus.Collector.Dependencies.Common.ListenerHandler public.

One scenario for this feature: I'm implementing DiagnosticSource instrumentation for my component and want to test out how it will work with OpenCensus.

**Comment by jacostro** [comment]
Our scenario:
* .NET Core web app code instrumented with DiagnosticListeners; this includes calls to ElasticSearch and Google DataStore,
* logging traces to Google StackDriver, with references to StackDriver Logging,
* using OpenCensus collectors for incoming and outgoing HTTP connections, and for Redis.

Providing a base for external collectors was something I was going to raise. The way OpenCensus.Collector.Dependencies and OpenCensus.Collector.AspNetCore collectors shared the same source files looked like temporary solution.

**Comment by SergeyKanzhelev** [comment]
Moved to OpenTelemetry
