### ISSUE TITLE
Running samples

### ISSUE THREAD

**Issue by hananiel** [census-instrumentation/opencensus-csharp#136]
Steps taken: 
git clone https://github.com/census-instrumentation/opencensus-node.git
cd src/Samples
dotnet run zipkin --uri=http://localhost:9411/api/v2/spans

Expected: Trace data in the zipkin ui
What happened: No traces, no errors or warnings 

Node sample works fine with same url.

**Comment by francisminu** [comment]
Any update on this one? I am facing the same issue when I use this library in my application.
I also tried cloning the repository and then followed the steps to build and run the application. I get the messages on the console 'About to do a busy work', 'Doing busy work' (10 times). And then when I check the traces at the Zipkin UI (localhost:9411), I do not see any traces/spans there.

**Comment by lmolkova** [comment]
I've been playing with it recently and know how to fix it. Will send PR  today.
