### ISSUE TITLE
Record stats in HttpClient listener

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-csharp#141]
see how it's done in [Java](https://github.com/census-instrumentation/opencensus-java/blob/master/contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpClientHandler.java#L155) and [specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/HTTP.md)

**Comment by SergeyKanzhelev** [comment]
moved to OpenTelemetry
