### ISSUE TITLE
Performance and benchmarking

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-csharp#15]
1. we should understand the performance of OC and fix bottlenecks if any
2. we should make it easy to run and experiment (e.g. opencensus-java allows to run benchmarking as unit tests) - can we do it?

**Comment by SergeyKanzhelev** [comment]
I'd suggest to use https://benchmarkdotnet.org/

**Comment by SergeyKanzhelev** [comment]
Moved to OpenTelemetry
