### ISSUE TITLE
Implement ApplicaitonInsights exporter

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-csharp#18]
Implement exporter to local forwarder (grpc, using https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/exporter/exporter.proto)

**Comment by lmolkova** [comment]
More context on this:

LocalForwarder or OpenCensus-service is agent that runs next to the app and forwards spans to a configurable backend.  
https://github.com/Microsoft/ApplicationInsights-LocalForwarder
https://github.com/census-instrumentation/opencensus-service

Every opencensus implementation should have exporter that sends data to the agent over gRPC + protobuf. Then vendor-specific exporter could be implemented only once for the agent.

LocalForwarder already implements advanced ApplicaitonInsights support with LiveStream, sampling and advanced telemetry channel.

This task involves ocagent exporter implementation in C#. As a result, running the OC-csharp with LocalForwarder will enable full AppInsights support.

Existing implementations:
- python: https://github.com/census-instrumentation/opencensus-python/tree/master/opencensus/trace/exporters/ocagent
- golang https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/master/ocagent.go
- java https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/trace/ocagent
- node https://github.com/census-instrumentation/opencensus-node/tree/master/packages/opencensus-exporter-ocagent
- out-of-date csharp prototype: https://github.com/lmolkova/opencensus-csharp/tree/lmolkova/grpcexporter/src/Steeltoe.Management.OpenCensus/Impl/Trace/Export/Grpc.


Detailed steps:

1. Get latest protobuf definitions https://github.com/census-instrumentation/opencensus-proto/tree/master/src/opencensus/proto
2. compile with protoc https://github.com/Microsoft/ApplicationInsights-LocalForwarder/blob/e4af977c247006ba82898a01bbf08403573d8732/src/Library/Contracts/opencensus/proto/generate_code.bat
3. Implement conversion from SpanData to Span proto. User python implementation as reference https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/exporters/ocagent/utils.py#L23

**Comment by SergeyKanzhelev** [comment]
This seems to be complete now. Closing
