### ISSUE TITLE
Should the concrete classes be hidden?

### ISSUE THREAD

**Issue by ndrwrbgs** [census-instrumentation/opencensus-csharp#28]
In the java source version, the concrete classes are created by [AutoValue](https://github.com/google/auto/tree/master/value) which, from my limited understanding, does not expose the concrete types. If we want to preserve that intention, then I'd propose our concrete classes (like `BucketBoundaries`, should not be `sealed`, but rather be `static` with just the `Create` method, and have `private sealed` implementation classes.

If the intention is to expose these concrete types (which may result in folks programming to those rather than the intended interfaces) then that's fine too - but at that point we may want to consider if we want to expose interfaces at all.

**Comment by SergeyKanzhelev** [comment]
This will be handled in OpenTelemetry project
