### ISSUE TITLE
Improve performance of CurrentStatsState

### ISSUE THREAD

**Issue by ndrwrbgs** [census-instrumentation/opencensus-csharp#30]
**Motivation**: Performance
**User impact**: None/Hypothetical

Oops, that wasn't meant to make it in as-is, mostly just to demonstrate the problem with the test :)

RE: #29, a lock is being taken for every read. We should investigate alternative methods as the type has the concurrency properties of being unlikely to be written to frequently (in fact, it's disallowed) and being likely to be read more than it is written. _Perhaps_ ReaderWriterLock would be sufficient here.

**Comment by SergeyKanzhelev** [comment]
this will be addressed in OpenTelemetry project
