### ISSUE TITLE
Remove or implement CurrentStatsState.set_Value

### ISSUE THREAD

**Issue by ndrwrbgs** [census-instrumentation/opencensus-csharp#31]
**Motivation**: Exposed API
**User impact**: Confusion

The `Value` property on an instance of `CurrentStatsState` exposes an empty `set` method. Either
1. That property setter should call `Set(StatsCollectionState state)`
1. That property setter should be removed
1. That property setter should have modified visibility to hide it from consumers

**Comment by lmolkova** [comment]
Set is actually quite useful, as we found with System.Diagnostics.Activity. 
In cases when async execution context is not preserved (HTTP requests on desckop, WCF or Asp.NET ) having public setter is essential.

**Comment by ndrwrbgs** [comment]
Hi @lmolkova! That'd be wonderful if you need to preserve or set the value - but note the implementation today - it's a NOOP :) If the Activity code was depending on this NOOP for functionality then that sounds like something weird indeed is going on.

**Comment by ndrwrbgs** [comment]
To clarify, I am speaking about `set_Value` https://github.com/census-instrumentation/opencensus-csharp/blob/424132081c256dd7433635bdad7f5b29c241b6d3/src/OpenCensus/Impl/Stats/CurrentStatsState.cs#L38, not `Set` https://github.com/census-instrumentation/opencensus-csharp/blob/424132081c256dd7433635bdad7f5b29c241b6d3/src/OpenCensus/Impl/Stats/CurrentStatsState.cs#L53.

**Comment by lmolkova** [comment]
@ndrwrbgs thanks for the clarification. 
Activity is .NET Span and uses AsyncLocal for the same purposes as OC. I just envision the need for set and it shouldn't be noop.

**Comment by SergeyKanzhelev** [comment]
This will be handled in OpenTelemetry project
