### ISSUE TITLE
Documentation on docs.microsoft.com

### ISSUE THREAD

**Issue by ndrwrbgs** [census-instrumentation/opencensus-csharp#36]
Mostly for @lmolkova (I think). I found this doc while looking for something else https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/tracing-and-instrumenting-applications and it looks like it's saying for dotnet to use `Trace` and doesn't mention `Activity`. There may be reasons for this I just wanted to put it on your radar.

**Comment by lmolkova** [comment]
@ndrwrbgs thanks for bringing it to my attention.  Activity is a relatively new API and the doc is out of date. We have a lot of different approaches for logging/debugging/tracing in .NET and it creates a lot of confusion. I agree we should improve the documentation and provide some clarity on what and where each tracing method is applicable. 

I've created the issue on docs.ms.com to address it https://github.com/dotnet/docs/issues/7311
