### ISSUE TITLE
Discuss releases schedule

### ISSUE THREAD

**Issue by SergeyKanzhelev** [census-instrumentation/opencensus-csharp#5]
This is the issue to collect feedback on releases schedule for this repository. Current thinking is to schedule releases like one beta every month and stable version twice a year. Basically calendar-based, not feature based.

We will also align marking SDK 1.0 with other repositories.

**Comment by ndrwrbgs** [comment]
Given there is a v0, is there plans to release this for initial usage on nuget - or are there blocking issues. If there are blocking issues for this, could they please be organized under a Milestone?

**Comment by ctaggart** [comment]
You may wish to revisit the semantic versioning of releases. nuget.org definitely support semver 2 in the prerelease part. I'm hoping MyGet also supports it. Right now the readme says the latest from MyGet is `0.1.0-beta1-4002` from September 7th. If you use `0.1.0-beta1.4002` it would probably work with a period separator.

**Comment by SergeyKanzhelev** [comment]
@ctaggart  I cleaned up MyGet. There were some high version packages stuck on top

**Comment by ctaggart** [comment]
@SergeyKanzhelev, that looks much better. Is it every `master` branch build that posts there?

**Comment by SergeyKanzhelev** [comment]
every `develop`.

**Comment by SergeyKanzhelev** [comment]
Project is being sunsetted.
