### ISSUE TITLE
Prometheus exporter not listening on all addresses

### ISSUE THREAD

**Issue by ekarlso** [census-instrumentation/opencensus-csharp#51]
I am assuming this should work but it doesnt listen on anything related to port 9184 then, if I change it to `localhost` instead of `0.0.0.0` then it works. Is it a bug or intentional?

``` csharp
var exporter = new PrometheusExporter(
new PrometheusExporterOptions()
{
    Url = new Uri("http://0.0.0.0:9184/metrics/")
},
Stats.ViewManager);

exporter.Start();
```

**Comment by SergeyKanzhelev** [comment]
Come again. Is it working with `localhost` and NOT working with `0.0.0.0` or other way around?

**Comment by ekarlso** [comment]
@SergeyKanzhelev Sorry for the late answer :) It's not listening on all addresses when 0.0.0.0 is specified. It seems to be listening on no addresses then.

**Comment by SergeyKanzhelev** [comment]
Moved to OpenTelemetry
