### ISSUE TITLE
Make byte array ToString efficient

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-csharp#53]
[ByteToHexCharArray](https://github.com/census-instrumentation/opencensus-csharp/blob/00144079aa03f67ef9e8bcf2478a9325d711464a/src/OpenCensus/Utils/Arrays.cs#L88) seems to be extremely inefficient with all allocations it does. Here is a wonderful perf analysis comparison for different algos to convert byte array to string https://stackoverflow.com/questions/311165/how-do-you-convert-a-byte-array-to-a-hexadecimal-string-and-vice-versa

we should do this: https://stackoverflow.com/questions/311165/how-do-you-convert-a-byte-array-to-a-hexadecimal-string-and-vice-versa/24343727#24343727

**Comment by lmolkova** [comment]
Another good option is `Guid.NewGuid().ToString("n")`

**Comment by miknoj** [comment]
Hello, if no one has picked up this issue for the hackathon, I would love to work on this for my first issue!
