### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by SergeyKanzhelev** [census-instrumentation/opencensus-csharp#6]
Let's try to start with CircleCI to align with other repos.

**Comment by SergeyKanzhelev** [comment]
CircleCI doesn't support .NET builds.
Travis only builds on Linux and uses mono. We need both
Standard VSTS doens't build from [forks](https://docs.microsoft.com/en-us/vsts/pipelines/build/ci-public?view=vsts&tabs=github#validate-contributions-from-forks) now.

I'll keep working on it. So far I enabled CI that will trigger from branches and will not show build logs. I will trigger it manually for big PRs from forks.

If this will take too much time - I'll make it work with travis.

**Comment by Falco20019** [comment]
Looked into Travis (for Linux) + AppVeyor (for Windows)?

**Comment by SergeyKanzhelev** [comment]
Made travis for forks validation and VSTS for CI
