### ISSUE TITLE
Prometheus exporter: allow to work via the application's port

### ISSUE THREAD

**Issue by SergeyKanzhelev** [census-instrumentation/opencensus-csharp#65]
In some environments opening separate port for Prometheus exporter will not work. Especially for sandboxed environments like Azure Web Apps. Re-using app's port and allow Prometheus to work as a middleware will help to enable those environments.

**Comment by orthros** [comment]
I'm looking at this right now. 

When you mention "middleware" are you referring to MVC middleware? e.g.
```csharp
public class Startup
{
    public void Configure(IApplicationBuilder app)
    {
        app.UsePrometheus(new PrometheusMiddlewareOptions(){ Url = new Uri("/metrics") });

        app.UseMvc();
    }
}
```

I ask, as I have written a version of this, but I am getting compiler warnings that the classes needed to register as MVC middleware (`HttpContext`, `IApplicationBuilder`, etc.) are not Common Language Specification compliant. Is this a strict compliance rule for this set of libraries? Have I mis-understood the requirement, or should I make a separate DLL that does not have the `[assembly: System.CLSCompliant(true)]` directive?

Thank you!

**Comment by SergeyKanzhelev** [comment]
just remove this directive. I was trying to use it whenever it can be used as it simplifies some cross-.NET- language scenarios. But it is not strictly required.

Thank you for looking into it!

**Comment by SergeyKanzhelev** [comment]
Moved to OpenTelemetry
