### ISSUE TITLE
Implement metrics and resource specifications

### ISSUE THREAD

**Issue by simonz130** [census-instrumentation/opencensus-csharp#67]
Currently we don't have metrics and resource specifications implemented:
https://github.com/census-instrumentation/opencensus-specs/blob/master/metrics/Metrics.md
https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/metrics/v1/metrics.proto

**Comment by SergeyKanzhelev** [comment]
This is for Open Census Service exporter, correct?

**Comment by SergeyKanzhelev** [comment]
Project is being sunsetted. APIs will be implemented in OpenTelemetry project
