### ISSUE TITLE
Add .net 4.5 target for abstractions and implementation

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-csharp#69]
Currently opencensus targets 4.6 and netstandard 2.0.
.NET 4.5 is not officially supported by Microsoft, but still is very popular.

Caveat: `AsyncLocal` is not available on .NET 4.5. 

[Here is the code](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.Current.net45.cs) that `System.Diagnostics.Activity` uses instead. Note what it does to avoid cross AppDomain calls issues.

**Comment by SergeyKanzhelev** [comment]
Why do we need to move implementation as well? Implementation should be used by apps where we can request upgrade to `net46`, not libraries which are quite limited in their options

**Comment by SergeyKanzhelev** [comment]
Let's see if we will need this for implementation. Closing for now
